name: Check in

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build image"]
    types:
      - completed

  # UTC时间，对应Beijing时间 9：30
  # schedule:
  #   - cron: "30 1 * * *"

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: enwaiax/smzdm_bot
      env:
        ANDROID_COOKIE: ${{ secrets.ANDROID_COOKIE }}
        TOKEN: ${{ secrets.TOKEN }}
        SK: ${{ secrets.SK }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
        PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        SC_KEY: ${{ secrets.SC_KEY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
    steps:
      - name: Working
        run: |
          python /smzdm_bot/main.py
